### ISSUE TITLE
Check task

### ISSUE THREAD

**Issue by AIRAT1** [AIRAT1/megaphone-tariff-catalog#2]

**Comment by coursar** [comment]
Вы решили принципиально не использовать Lombok? ))

**Comment by AIRAT1** [comment]
Кроме Немчинского много кто против использования ламбока. Например в конце этой статьи https://medium.com/@vgonzalo/dont-use-lombok-672418daa819 пишется что профита от использования ламбока не много. Ещё когда кодил под андроид не понимал зачем нужен такой синтаксический сахар типа ButterKnife. Если в учебных целях его обязательно нужно использовать, то, конечно же в учебные проекты готов добавить ломбок.
