### ISSUE TITLE
Что означает суффикс Group? Если он описывает тарифы, то должно быть этого суффикса, а если группы тарифов, то ок

### ISSUE THREAD

**Issue by coursar** [AIRAT1/megaphone-tariff-catalog#3]
https://github.com/AIRAT1/megaphone-tariff-catalog/blob/c02f852acbf21ebe83aa99f9a4c2607ca8bd1beb/src/main/java/ru/itpark/model/BaseTariffGroup.java#L3

Но по коду - он описывает тарифы

**Comment by AIRAT1** [comment]
Классы с суффиксом Group должны описывать группы тарифов. Конкретные тарифы должны создаваться наследованием от конкретного абстрактного ...Group класса. Который в свою очередб наследуется от абстрактного BaseGroup. Поясните, пожалуйста что у меня не так в коде - ...Group классов. Спасибо!
